# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iisc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
